PY=python3
NAME=CFM5_pilot_bspline
VERSION=beta_1.2
YEAR=2018
cfm=/usr/local/CFM5_release_2017/obj/CFM5_preferred/native
out=output2

### General options
# show_plot : Show figures that are being generated. When enabled, user
# interaction is required. Plot window must be closed to resume operation
show_plot = 1

### Options for mesh conversion
# min_elem : Minimum number of elements a triangular surface must contain to
# get processed
min_elem = 20


### Options for BSpline fitting
# bnd_degree : Polynomial degree
# residual : Desired residual to obtain. More control points are inserted until
# 	this threshold is reached
# bnd_smooth : Amount of smoothness to add in the fitting. FIXME: this feature
# does not yet work.
# bnd_refinement_ratio : Refine sides with unbalanced number of nodes compared
# 	to opposing side. Refinement inserts points at midpoints.
# surf_smooth : Amount of smoothness to add to surface fitting.
# surf_invert_mapping : Determine UV-mapping by inverting the transfinite
# 	interpolation mapping.
bnd_degree = 3
bnd_residual = 1.0
bnd_smooth = 0
bnd_refinement_ratio = 3
surf_smooth = 0.2
surf_invert_mapping = 0

# List of faults to process
# Each fault is processed sequentially by calling `make num=1`
# where `num` is the index of the fault in the array.
num=1
fault1=PNRA-CRSF-USAV-Fontana_Seismicity_lineament-CFM1
fault2=GRFS-GRFZ-WEST-Garlock_fault-CFM5
fault3=WTRA-NCVS-VNTB-Southern_San_Cayetano_fault-steep-JHAP-CFM5
fault4=WTRA-ORFZ-SFNV-Northridge-Frew_fault-CFM2
fault5=WTRA-SSFZ-MULT-Santa_Susana_fault-CFM1
fault6=SAFS-SAFZ-MULT-Garnet_Hill_fault_strand-CFM4
fault7=SAFS-SAFZ-COAV-Southern_San_Andreas_fault-CFM4
fault8=WTRA-SFFS-SMMT-Santa_Monica_fault-steep-CFM5
fault9=WTRA-SBTS-SMMT-Santa_Monica_thrust_fault-CFM1
fault10=PNRA-NIRC-LABS-Newport-Inglewood_fault-dip_w_splays-split-CFM5
fault11=PNRA-CSTL-SJQH-San_Joaquin_Hills_fault-truncated-CFM3
fault12=PNRA-CEPS-LABS-Compton-Los_Alamitos_fault-CFM2
faults=$(fault1) $(fault2) $(fault3) $(fault4) $(fault5) $(fault6) $(fault7) \
       $(fault8) $(fault9) $(fault10) $(fault11) $(fault12)
fault=$(word $(num), $(faults)).msh

include Makefile
